### ISSUE TITLE
Complete the checks for reserved words and symbols

### ISSUE THREAD

**Issue by am-cid** [Gidsss/UwUIDE#10]
Currently implemented
- `bweak`
- `chan`
- `cap`
- `~`
- `-` as id_delim and unary but not other uses, still need to add that
- Identifiers, not function names, still need to add that

**Comment by HolyShaq** [comment]
going to work on symbols

**Comment by Gidsss** [comment]
> going to work on symbols

Yeah, I'll go work on reserved words naman

**Comment by am-cid** [comment]
### new on my side (needed for testing)
- `fwunc`

kindly skip working on this
