### ISSUE TITLE
Parser Production Methods for GUI Integration

### ISSUE THREAD

**Issue by chaaals** [Gidsss/UwUIDE#105]
## Description
Kindly make methods for each production that prints properties that we would like to show in our parser gui.

## Mainuwu
- [ ] method for printing parameters
- [ ] method for printing body

## Functions
- [ ] public access for function id
- [ ] method for printing parameters
- [ ] method for printing body

## Globals
- [ ] public access for id, type, and value

## Classes
- [ ] public access for id
- [ ] method for printing parameters
- [ ] method for printing methods
- [ ] method for printing body

**Comment by am-cid** [comment]
see #109 and #113

for more requests, please open up a new issue
