### ISSUE TITLE
String concat op `&` should be on the same level as sum ops

### ISSUE THREAD

**Issue by am-cid** [Gidsss/UwUIDE#135]

**Comment by HolyShaq** [comment]
Ok will fix later this evening, di ako sure where to put it before eh

**Comment by HolyShaq** [comment]
Is there a reason why it can't be on a separate level tho?

**Comment by am-cid** [comment]
Because python does not have a concat operator. It uses `+` for both. Since we're transpiling both our `+` and `&` to python's `+`, ours should be on the same level.

**Comment by HolyShaq** [comment]
Ah that makes sense okokok

**Comment by am-cid** [comment]
see commit 0290d7898379d6de589de37b70bf67aa9ef0d157
Closing this
