### ISSUE TITLE
\n not getting transpiled properly

### ISSUE THREAD

**Issue by HolyShaq** [Gidsss/UwUIDE#215]

**Comment by am-cid** [comment]
- [x] solved. 

before transpiling to python to be compiled, do this regex sub
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/e9e259a1-56ef-4b8f-918d-b46651d298fe)

this assumes that the source code was read raw
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/78d81f03-89ec-4302-8a79-648c00a7d8ff)

---

### output:
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/2bf1c520-e58b-428f-83de-f6fa2ac3bc22)

### output without regex sub:
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/00d54f25-786d-4789-a75b-c83bd2aa0b40)

---
cc: @chaaals @Gidsss
