### ISSUE TITLE
Floor/ceil integer and float literals (chan and kun)

### ISSUE THREAD

**Issue by Gidsss** [Gidsss/UwUIDE#241]
## Integer literals

- -9999999999 (floor value) 

- 9999999999 (ceiling value)

## Float literals
- -9999999999.9999999999 (floor value) -> -9999999999.0
- 9999999999.9999999999 (ceiling value) -> 9999999999.0

Note: Values greater than the given ceiling value will be adjusted to the ceiling value while values less than the floor value will be adjusted to the floor value.

**Comment by am-cid** [comment]
Solution is to implement a builtin fn that automatically floors/ceils int/float values.

something like `to_float()` or `to_int()`

**Comment by am-cid** [comment]
new solution is to have builtin types so capping values also happens during operations (+, - *, /, %), not just assignments and declarations
