### ISSUE TITLE
fix how unique identifiers are displayed in lexer tab

### ISSUE THREAD

**Issue by am-cid** [Gidsss/UwUIDE#245]
## current
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/59fc6933-cda9-4e13-a334-b3c3f6f021dc)
needs to be cwass_n, id_n

---
### solution: change what property gui uses to display `Token`
used to be `self.token` but i changed implementation. now the `id_n` and `cwass_n` is in `self.unique_type`
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/ad0cefe4-aaf4-47e4-8924-08cc15e155f6)

if `self` is `Token`, do `self.token.unique_type`
if `self` is `UniqueTokenType`, do `self.unique_type`
not sure what you guys are using there.

**Comment by chaaals** [comment]
I can work on this if not taken

**Comment by am-cid** [comment]
Merged #253, closing this
