### ISSUE TITLE
Fix code formatter ui handling and display unstyled semantic errors

### ISSUE THREAD

**Issue by chaaals** [Gidsss/UwUIDE#250]
## Description
Since same context (ConsoleView), I'll put them both on the same issue. Formatting code that has errors saves the error states once resolved. It should clean up the error states upon successful formatting. Additionally, display unstyled semantic errors.

## Preview
**Code formatter**
- First run w/ errors
![Screenshot 2024-05-02 223110](https://github.com/Gidsss/UwUIDE/assets/70326902/65e3dc7b-ed00-4677-8b04-7d4d00337e10)
![Screenshot 2024-05-02 223118](https://github.com/Gidsss/UwUIDE/assets/70326902/ad6bfbc9-83db-4de7-86c2-df5eefe89fbb)

- Second run w/ resolved errors
![Screenshot 2024-05-02 223130](https://github.com/Gidsss/UwUIDE/assets/70326902/38c9485f-cee5-49b1-9053-524f3779fbeb)
![Screenshot 2024-05-02 223137](https://github.com/Gidsss/UwUIDE/assets/70326902/ffbe0f72-fc79-4f08-90b1-7175fc221669)

**Styled Semantic Errors**

![Screenshot 2024-05-02 224951](https://github.com/Gidsss/UwUIDE/assets/70326902/ed98979e-5a64-4be7-a50d-fbbe117f27d6)
![Screenshot 2024-05-02 224943](https://github.com/Gidsss/UwUIDE/assets/70326902/b5706abf-4605-4582-881c-21da651543ca)

**Comment by HolyShaq** [comment]
Oops, yep. I forgot lol.

**Comment by am-cid** [comment]
Merged #253, closing this
