### ISSUE TITLE
Fix code formatter logic on function/method calls

### ISSUE THREAD

**Issue by chaaals** [Gidsss/UwUIDE#251]
## Description
Found this while testing it out, but the formatter removes `tilde` on function/method calls once formatted.

## Preview
Before
![Screenshot 2024-05-02 225340](https://github.com/Gidsss/UwUIDE/assets/70326902/dec99d19-9597-4dd6-8fea-a47586e9d22e)
After
![Screenshot 2024-05-02 225349](https://github.com/Gidsss/UwUIDE/assets/70326902/f267f5dc-56fc-4b1a-af72-9dbf98166483)

**Comment by am-cid** [comment]
Are you sure it's just builtin methods? Please test out regular fn calls. 

cc @HolyShaq

**Comment by HolyShaq** [comment]
Will look into this. I remember having a problem with FnCalls doubling up on tildes so I think I may have wrongly accounted for it.

**Comment by am-cid** [comment]
Merged #254, closing this
