### ISSUE TITLE
Boolean inputs, wrong values

### ISSUE THREAD

**Issue by uzuriel** [Gidsss/UwUIDE#261]
**If has input for sama type (even if cap is the input [which is false value]), returns fax, 
if no input, returns cap**

>//< Using only a for loop, negates an input boolean 
value and then prints it given a number of times. >//<

fwunc mainuwu-san() [[
    bool-sama = inpwt("Enter boolean value [fax/cap]: ")~
    pwint(bool)~
]]

output: 

Enter boolean value [fax/cap]: cap
fax

**Comment by am-cid** [comment]
not going to fix, this is intended behavior
![image](https://github.com/Gidsss/UwUIDE/assets/146176671/723f171f-cfb5-4c13-bd26-bce82966e06c)
