### ISSUE TITLE
multiplying \ when format is clicked

### ISSUE THREAD

**Issue by uzuriel** [Gidsss/UwUIDE#263]
![image](https://github.com/Gidsss/UwUIDE/assets/116715187/2ee01999-e86a-4a60-9dd8-64a46b4f8a02)

once format is clicked:

![image](https://github.com/Gidsss/UwUIDE/assets/116715187/0a63e1cf-f2b8-48a9-9cad-aca29a13420a)

**Comment by am-cid** [comment]
merged #264, closing this
