### ISSUE TITLE
pow built in method does not accept Int

### ISSUE THREAD

**Issue by HolyShaq** [Gidsss/UwUIDE#271]
(on main branch)

Number.pow() can only accept literals.

Src Code:
```
fwunc mainuwu-san() [[
        a-chan = 1~
        b-chan = 2~
        pwint(a.pow(2))~
        pwint(a.pow(b))~
]]
```

Output:
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/28e9b8ac-e8b7-4518-9252-08119f861a75)

**Comment by am-cid** [comment]
more context please

**Comment by HolyShaq** [comment]
my bad, i thought it was more general aaa
