### ISSUE TITLE
Unexpected behavior: automatically assigning a default value of 1 to an array specified as [] when clicking format

### ISSUE THREAD

**Issue by Gidsss** [Gidsss/UwUIDE#290]
https://github.com/Gidsss/UwUIDE/assets/88811389/ab83cafc-c298-4a3e-9505-b49d481f9ded

**Comment by am-cid** [comment]
This is prolly expected behavior since functionality does not change
cc @HolyShaq please close as not planned if I'm correct

**Comment by HolyShaq** [comment]
Gids and I talked, and I feel like it'd be best if we format it the way the user typed the declaration so I'm planning on fixing it.

**Comment by am-cid** [comment]
closed #292, closing this
