### ISSUE TITLE
`quick run` button to skip compiling and run transpiled python directly 

### ISSUE THREAD

**Issue by am-cid** [Gidsss/UwUIDE#314]

**Comment by am-cid** [comment]
yes but this will not use `Compiler.compile()` then `Compiler.run()`. Instead, it will use `Compiler.run_python()` for quicker outputs

**Comment by Gidsss** [comment]
> yes but this will not use `Compiler.compile()` then `Compiler.run()`. Instead, it will use `Compiler.run_python()` for quicker outputs

I did this pero sa VS terminal lalabas yung result is that fine? like transpiled python na

**Comment by am-cid** [comment]
Thats good enough but much better if you can:
1. use `import tempfile` to create a temp python file
2. write `Compiler.source` there and get the file path
3. open up cmd and `python <file path>`

for more information, see how `Compiler.run_python()` is implemented. you can just replicate that behavior since `Compiler.run_python()` does not open up a cmd, hence maybe why its outputting to VS Terminal.
