### ISSUE TITLE
Bugs I found while making programs

### ISSUE THREAD

**Issue by HolyShaq** [Gidsss/UwUIDE#321]
I compiled to one issue nalang para di makalat

- [x] #322
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/9357c8ac-f16c-428a-9e22-2ef4cf968d56)
- [x] Indexed strings break when accessing its built-in methods @am-cid 
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/f74aa866-6df3-4a13-99d6-8fa903ef2f91)
- [x] Auto Format removes tilde on inpwts used as statement @HolyShaq 
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/03ab4e67-f1a1-402f-a2ef-9a2490953832)
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/d7ff4300-1cc7-467a-9ab1-584e72e5345f)

**Comment by am-cid** [comment]
Merged #324 #325 and #326, closing this
