### ISSUE TITLE
Implement token type module and complete the token types

### ISSUE THREAD

**Issue by am-cid** [Gidsss/UwUIDE#9]
Token types contain:
1. Lexeme
2. Token
3. Delim id
4. ErrorType

Example:
TokenType.BWEAK
1. "bweak"
2. "RESERVED_WORD" or "RESERVED_WORD_BWEAK" or "BWEAK"
3. "end"
4. ErrorType.BWEAK

passing it to self._peek() would be like
```
self._peek(*TokenType.BWEAK)
self._peek(*TokenType.CHAN)
self._peek(*TokenType.CAP)
```
___
also, complete the token types once implemented

**Comment by HolyShaq** [comment]
Response:
1. Yup. I don't think there's any problem with that, though. We can still assign a TokenType for ids and literals even if we won't use the peek method for them.
2. That would make a lot more sense. I will try and refactor that part of the code once I implement this.

**Comment by HolyShaq** [comment]
Would it make sense if this is implemented under the token module? I'm thinking of something like this.
![image](https://github.com/Gidsss/UwUIDE/assets/66175571/58e16784-eff4-4a63-a1ba-48b9c38b8d13)

**Comment by Gidsss** [comment]
Yeah, looks good and promising. I'm down.

> Would it make sense if this is implemented under the token module? I'm thinking of something like this. ![image](https://user-images.githubusercontent.com/66175571/279080876-58e16784-eff4-4a63-a1ba-48b9c38b8d13.png)

**Comment by HolyShaq** [comment]
Yep yep. Though, I'm making it so that the lexeme is independent from the token type class. Pacheck nalang sa branch ko if it makes sense HAHAHAHAH

[Commit 3 for my branch](https://github.com/Gidsss/UwUIDE/commit/94d96d6ab4b25cc7d76eab42c68e8df94e84747c)

**Comment by am-cid** [comment]
> Response:
> 
> 1. Yup. I don't think there's any problem with that, though. We can still assign a TokenType for ids and literals even if we won't use the peek method for them.

The problem with that is that this class takes in a lexeme argument and identifiers don't have a fixed lexeme



> Would it make sense if this is implemented under the token module? I'm thinking of something like this. ![image](https://user-images.githubusercontent.com/66175571/279080876-58e16784-eff4-4a63-a1ba-48b9c38b8d13.png)

use `__init__` instead of a subclass if you're going to stick to using Enum

```
from enum import Enum

class AClass(Enum):
    SAMPLE_CONSTANT = ("Sample arg 1", "Sample arg 2")

    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2

print(AClass.SAMPLE_CONSTANT.arg1) # prints "Sample arg 1"
```

**Comment by HolyShaq** [comment]
PR for this issue!!! #14
